{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.7.1-komorebi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.7.1-komorebi.aar",
          "url": "media3-exoplayer-1.7.1-komorebi.aar",
          "size": 1524538,
          "sha512": "36b279e0da778ad23012029aa7c797dd68cbd3a0e07e3861d9ffad92f4040448e3a38c5a9b09e431a90ab3b00885aca0f0c042332564d8ee66b0df5d45dd2913",
          "sha256": "78193302f942155e1490a57733940697e3927984fcb692fd95e65d859ebc1f68",
          "sha1": "6b68b84de8b74cb773e9d419f2acf1e8e95841a5",
          "md5": "6d502eea16282ec371512dec713e80a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.7.1-komorebi"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.7.1-komorebi.aar",
          "url": "media3-exoplayer-1.7.1-komorebi.aar",
          "size": 1524538,
          "sha512": "36b279e0da778ad23012029aa7c797dd68cbd3a0e07e3861d9ffad92f4040448e3a38c5a9b09e431a90ab3b00885aca0f0c042332564d8ee66b0df5d45dd2913",
          "sha256": "78193302f942155e1490a57733940697e3927984fcb692fd95e65d859ebc1f68",
          "sha1": "6b68b84de8b74cb773e9d419f2acf1e8e95841a5",
          "md5": "6d502eea16282ec371512dec713e80a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.7.1-komorebi-sources.jar",
          "url": "media3-exoplayer-1.7.1-komorebi-sources.jar",
          "size": 1105623,
          "sha512": "cbccc3d8b3d3ca493480a90d7ba4120062c064e95eddba4b303a3877f35b3540d3bfec83096ad3d735024f1e97527e7342dffdf1bbcef37c0bc7b7625203fbc9",
          "sha256": "4d59df7db417eb0d0eef8c4cfce59415964edb96a3fb862275c4aba65ea7949e",
          "sha1": "58d39cdf41cbcfb3a49b86ae724144abeae62a30",
          "md5": "6bb4eb6edb3aada244d827f9c703cc91"
        }
      ]
    }
  ]
}
